FROM node
WORKDIR /frontend
COPY ./frontend/package.json ./frontend/yarn.lock ./
RUN yarn
COPY ./frontend/vite.config.js ./vite-config.js
COPY ./frontend/index.html ./index.html
COPY ./frontend/src ./src
CMD yarn start
